Algoritmo "Tarefa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : André
// Descrição   : Tarefa
// Autor(a)    : Patrick Stegaribe de Almeida
// Data atual  : 24/03/2022
Var
   nome: caracter
   idade: inteiro

Inicio

   escreva("Nome: ")
   leia(nome)
   escreva("idade: ")
   leia(idade)
   escreva("Seu nome é ", nome," e sua idade é", idade)

Fimalgoritmo