Algoritmo "Tarefa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : André
// Descrição   : Tarefa
// Autor(a)    : Patrick Stegaribe de Almeida
// Data atual  : 24/03/2022
Var

   raio: real
   altura: real
   conta: real
   
Inicio

   escreva("Medida do raio: ")
   leia(raio)
   escreva("Medida da Altura: ")
   leia(altura)
   conta <- 3.14159 * (raio^2) * altura)
   escreva("O volume da lata de óleo é de: ", conta)
   
Fimalgoritmo