Algoritmo "Tarefa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : André
// Descrição   : Tarefa
// Autor(a)    : Patrick Stegaribe de Almeida
// Data atual  : 24/03/2022
Var
   base: real
   altura: real

Inicio

   escreva("Valor da base: ")
   leia(base)
   escreva("Valor da altura: ")
   leia(altura)
   escreva("A área de um triangulo é ", base*altura/2)
   
Fimalgoritmo