Algoritmo "Tarefa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : André
// Descrição   : Tarefa
// Autor(a)    : Patrick Stegaribe de Almeida
// Data atual  : 24/03/2022
Var

   numx: real
   numy: real
   x: real
   y: real
   

Inicio

   escreva("Numero 1: ")
   leia(numx)
   escreva("Numero 2: ")
   leia(numy)

   x <- numx-numx-numx
   y <- numy-numy-numy
   
   escreval("Numero 1: ", x)
   escreval("Numero 2: ", y)
   
Fimalgoritmo