Algoritmo "Tarefa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : André
// Descrição   : Tarefa
// Autor(a)    : Patrick Stegaribe de Almeida
// Data atual  : 24/03/2022
Var

   idade: inteiro
   meses: inteiro
   horas: inteiro

Inicio

   escreva("Idade da pessoal: ")
   leia(idade)
   
   meses <- idade*12
   horas <- meses*720
   
   escreval("Idade em meses: ", meses)
   escreval("Idade em horas: ", horas)

Fimalgoritmo