Algoritmo "Tarefa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : André
// Descrição   : Tarefa
// Autor(a)    : Patrick Stegaribe de Almeida
// Data atual  : 24/03/2022
Var
   SB: real
   DES: real
   AD: real


Inicio

    escreva("Salário bruto: ")
    leia(SB)
    escreva("Adicionais: ")
    leia(AD)
    escreva("Valor a descontar: ")
    leia(DES)
    escreva("O salário final  é de: ", SB+AD-DES)

   
Fimalgoritmo