Algoritmo "Tarefa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : André
// Descrição   : Tarefa
// Autor(a)    : Patrick Stegaribe de Almeida
// Data atual  : 24/03/2022
Var
   lado: real


Inicio

    escreva("Qual a medida de um lado do quadrado: ")
    leia(lado)
    escreval("O perimetro é de: ", lado*4)
    escreva("A base é de: ", lado*lado)

   
Fimalgoritmo