Algoritmo "Tarefa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : André
// Descrição   : Tarefa
// Autor(a)    : Patrick Stegaribe de Almeida
// Data atual  : 24/03/2022
Var
   notax: real
   notay: real
   notaz: real

Inicio

   escreva("nota 1: ")
   leia(notax)
   escreva("nota 2: ")
   leia(notay)
   escreva("nota 3: ")
   leia(notaz)
   escreva("Sua média é: ", (notax*2+notay*3+notaz*5)/10)

   
Fimalgoritmo